name: unicolor
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.7.13
  - pip=22.2
  - cudatoolkit=11.3
  - pytorch-cuda=11.6
  - torchvision
  - pip:
    - PyYAML==5.4.1
    - Pillow==9.2.0
    - pytorch-lightning==1.3.7.post0
    - opencv-contrib-python==4.6.0.66
    - kornia==0.5.11
    - requests==2.28.1
    - tqdm>=4.23.0
    - scipy==1.2
    - torchsummary>=1.3
    - matplotlib>=2.2.2
    - scikit_image>=0.15.0
    - torchviz>=0.0.1
    - easydict
    - prefetch_generator
    - tensorboard
    - future
    - numba
    - pypng
    - nltk
    - torchmetrics==0.5
    - ftfy
    - regex
    - git+https://github.com/openai/CLIP.git