name: chroma_vqgan_coco

log_dir: logs/vqgan_coco_t10

model:
  embed_dim: 512
  n_embed: 4096
  lr_decay: [100, 1.0]
  ddconfig:
    double_z: False
    z_channels: 512
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [16]
    dropout: 0.0

loss:
  disc_conditional: False
  disc_in_channels: 3
  disc_start: 5001
  disc_weight: 0.8
  codebook_weight: 1.0
  perceptual_weight: 1.0

data:
  train:
    split: 'train'
    batch_size: 6
    resolution: [256, 256]
    datapath: '/home/huangzhitong/dataset/coco'
    num_workers: 12
    meta_files: ['train2017_meta.json', 'unlabeled2017_meta.json']
    threshold: 10.0
  val:
    split: 'val'
    batch_size: 6
    resolution: [256, 256]
    datapath: '/home/huangzhitong/dataset/coco'
    num_workers: 12
    meta_files: ['val2017_meta.json']
    threshold: 10.0

train:
  steps: 5000000
  log_steps: 1
  ckpt_steps: 10000
  learning_rate: 7.5e-5
  accumulate_grad_batches: 1
  gpus: [0, 1, 2, 3]
  precision: 16  # can be 16 or 32
  from_checkpoint: Null
