name: vqgan

log_dir: /home/ma-user/work/wc_utils/logs/vqgan_imagenet_old

model:
  embed_dim: 512
  n_embed: 4096
  lr_decay: [100, 1.0]
  ddconfig:
    double_z: False
    z_channels: 512
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [16]
    dropout: 0.0

loss:
  disc_conditional: False
  disc_in_channels: 3
  disc_start: 6001
  disc_weight: 0.8
  codebook_weight: 1.0
  perceptual_weight: 1.0
  vgg16_path: '/home/ma-user/work/wc_utils/input/vgg16/vgg16.pth'

dataset:
  name: imagenet
  batch_size: 8
  color: 'rgb'
  resolution: [256, 256]
  datapath: '/home/ma-user/work/wc_utils/input/imagenet'
  num_workers: 32
  threshold: 10.0
  patch_size: [16, 16]

train:
  steps: 5000000
  log_steps: 1
  base_learning_rate: 1.6e-6
  accumulate_grad_batches: 1
  gpus: 4
  precision: 16  # can be 16 or 32
  from_checkpoint: Null
